mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('polls/',include('polls.urls')),
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.urls import  path
from django.views.generic import  TemplateView
from . import  views

app_name = 'polls'

urlpatterns = [
    path('details/<int:question_id>',views.detailView,name = 'details'),
    path('list_quest/',views.viewlist,name='view_list'),
    path('',views.index,name='index'),
    path('<int:question_id>',views.vote,name='vote'),
]

mysite/polls/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    time_pub = models.DateTimeField()
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=100)
    vote = models.IntegerField(default=0)

mysite/polls/views.py
from django.shortcuts import render
from django.http import  HttpResponse
from .models import Question
# Create your views here.

def index(request):
    myname = "Minh An"
    profile1 = ["Điện thoại","máy tính","Máy bay","nhiều tiền"]
    context = {"name":myname,"profile" :profile1}
    return render(request, "polls/index.html",context)

def viewlist(request):
    list_question = Question.objects.all()
    context = {"list_quest":list_question}
    return render(request,"polls/question_List.html",context)

def detailView(requset,question_id):
    q = Question.objects.get(pk = question_id)
    return render(requset,'polls/details_question.html',{'qs' : q})

def vote(request,question_id):
    q = Question.objects.get(pk = question_id)
    try:
        data = request.POST["choice"]
        c = q.choice_set.get(pk=data)
    except:
        HttpResponse("Loi khong co choicce")
    c.vote = c.vote + 1
    c.save()
    return render(request,'polls/result.html',{'q' : q})

mysite/polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
    <title>{% block title %}{% endblock  %}</title>

</head>
<body>
    <div class="container-fluid" style="min-height:95%">
        <div class="header"><h1 style="text-align:center">Website làm bằng python django</h1></div>
        <div class="menu">
            <ul>
                <li><a href="{% url 'polls:index' %}">Home</a></li>
                <li><a href="{% url 'polls:view_list' %}">Danh sách</a></li>
                <li><a href="">Chi tiết</a></li>
                <li><a href="">Liên hệ</a></li>
            </ul>
        </div>
        <div class="content">
            {% block content %}

            {% endblock %}
        </div>
    </div>
 <footer>
    <div class="container-fluid">
        <a href="">Facebook</a>|
        <a href="">Twiter</a>|
        <a href="">Google+</a>
    </div>
 </footer>
</body>
</html>

mysite/polls/templates/polls/details_question.html
{% extends 'polls/base.html' %}
{% block content %}
    {% if qs %}
    <form action="{% url 'polls:vote' qs.id %}" method="post">
        {% csrf_token %}
        <ul>
        {% for item in qs.choice_set.all %}
            <li><input type="radio" value="{{ item.id }}" name="choice">{{ item.choice_text  }}</li>
        {% endfor %}
            <p><input type="submit" value="Gui"></p>
        </ul>
    </form>
    {% endif %}
 {% endblock %}

mysite/polls/templates/polls/index.html
{% extends 'polls/base.html' %}
{% block content %}
{% load staticfiles %}
 <div class="row">
    <div class="col-sm-2">
        <center><img src="{% static 'images/logo.jpg' %}" class="responsive-img" style="max-height:200px" alt=""></center>
    </div>
    <div class="col-sm-10">
       <h1>Đây là template</h1>
        <p>Chào các bạn mình là  <b>{{ name }}</b></p>
        <h2>Profile của tôi gồm: </h2>
        <ul>
        {% for item in profile %}
            <li>{{ item }}</li>
        {% endfor %}
        </ul>
    </div>
 </div>
 {% endblock %}

mysite/polls/templates/polls/question_list.html
{% extends 'polls/base.html' %}
{% block content %}
<h2>Danh sách câu hỏi!</h2>
    {% if list_quest %}
        {% for item in  list_quest %}
            <a href="{% url 'polls:details' item.id %}"><p>{{ item.question_text }}</p></a>
        {% endfor %}
    {% else %}
        <h3 style="color:red">no data</h3>
    {% endif %}

{% endblock %}

mysite/polls/templates/polls/result.html
{% extends 'polls/base.html' %}
{% block content %}
<div class="row1"  style="text-align:center">
    {% if q %}
        <h3> Question: {{ q.question_text }}</h3>
        <p>Kết quả của cuộc bình chọn là :</p>
        {% for item in q.choice_set.all %}
            <p>{{ item.choice_text}} : <span style="color:red">{{ item.vote}}</span> </p>
        {% endfor %}
        <a href="{% url 'polls:view_list' %}">Vote tiếp</a>
    {% endif %}
</div>
{% endblock %}